require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    config.public_file_server.headers = { "cache-control" => "public, max-age=#{2.days.to_i}" }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  # config.active_storage.service = :local  # ❌ Disabled - Active Storage not loaded

  # Don't care if the mailer can't send.
  # config.action_mailer.raise_delivery_errors = false  # ❌ Disabled - Action Mailer not loaded

  # Make template changes take effect immediately.
  # config.action_mailer.perform_caching = false  # ❌ Disabled - Action Mailer not loaded

  # Set localhost to be used by links generated in mailer templates.
  # config.action_mailer.default_url_options = { host: "localhost", port: 3000 }  # ❌ Disabled - Action Mailer not loaded

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Use Solid Queue for background jobs (same as production)
  config.active_job.queue_adapter = :solid_queue

  # Enable verbose logging for Solid Queue in development
  config.log_level = :debug

  # Log to both file and STDOUT so bin/dev shows worker job logs
  stdout_logger = ActiveSupport::Logger.new(STDOUT)
  stdout_logger.formatter = ActiveSupport::Logger::SimpleFormatter.new

  file_logger = ActiveSupport::Logger.new(Rails.root.join("log", "development.log"))
  file_logger.formatter = ActiveSupport::Logger::SimpleFormatter.new

  # Broadcast to both destinations
  config.logger = ActiveSupport::BroadcastLogger.new(stdout_logger, file_logger)

  # Solid Queue uses main Rails logger
  config.solid_queue.logger = config.logger

  # Highlight code that triggered redirect in logs.
  config.action_dispatch.verbose_redirect_logs = true

  # Suppress logger output for asset requests.
  config.assets.quiet = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Allow Action Cable access from any localhost port in development
  config.action_cable.disable_request_forgery_protection = true
  config.action_cable.allowed_request_origins = [ /http:\/\/localhost:\d+/, /http:\/\/127\.0\.0\.1:\d+/ ]

  # Default URL options for url helpers (used in background jobs, mailers, etc.)
  config.action_mailer.default_url_options = { host: "localhost", port: 3001, protocol: "http" }
  Rails.application.routes.default_url_options = { host: "localhost", port: 3001, protocol: "http" }

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
end
